### ISSUE TITLE
Playing Video

### ISSUE THREAD

**Issue by onos9** [ZoidTechnology/PanelPlayer#1]
Is there a feature to send video to the colorlight 5a-75b. OR please I need a guide on sending  video frames to the board.

**Comment by ZoidTechnology** [comment]
Thanks for your interest in the project! You're able to send video to the 5A-75B with PanelPlayer provided it's in WebP format - this means no audio. You'll first need to compile PanelPlayer. On Ubuntu this would be something like:

1. Clone the repository with `git clone https://github.com/ZoidTechnology/PanelPlayer.git`
2. Change directory to the cloned repository with `cd PanelPlayer`
3. Install libwebp with `apt install libwebp-dev`
4. Build PanelPlayer with `make`
5. Enter the build directory with `cd build`

Once you've built PanelPlayer you can run it with `./panelplayer -p <ethernet port> -w <display width> -h <display height> video.webp`. Depending on your configuration you might need to run it with `sudo`.
