### ISSUE TITLE
No picture on card. Works fine with ledvision.

### ISSUE THREAD

**Issue by jannoke** [ZoidTechnology/PanelPlayer#2]
I get no reaction on the panel. I can see from tcpdump that packets are going out. How is it even meant to work on on multiple cards? Should I targer broadcast on specific mac address instead of default on code?

Running on rpi3 with :
./panelplayer -p wlan0 -w 32 -h 16 -b 10 -s ezgif-2-4f97098d37.webp

**Comment by ZoidTechnology** [comment]
You'll have to make sure you're using a Raspberry Pi with Gigabit Ethernet, as the receiving cards don't support other speeds. This means you'll need to use at least a Pi 3 B+. All the receiving cards appear to use the same MAC address, so it shouldn't need to be changed.

You'll want to make sure you're using the correct port when launching PanelPlayer. Brightness is specified between 0 and 255, so 10 could be a bit dark depending on the content and display you're using. Give this a try:

    ./panelplayer -p eth0 -w 32 -h 16 -s ezgif-2-4f97098d37.webp

**Comment by ZoidTechnology** [comment]
Your compiler doesn't seem to realise `update()` is never used unless initialised. You should be able to remove `-Wall -Werror` from `source/makefile` as a fix.

Often Colorlight requires a packet that isn't a valid Ethernet frame. Some NICs/drivers appear to drop these frames. I wouldn't be surprised if some VM implementations also have trouble with them.

The entire image is broadcast over the network. When you configure a receiver in LEDVision you set its position and size. The receiver will then display that region of the image. Multiple receiving cards can be daisy chained or connected to a layer 2 switch. You might have issues using a switch that drops malformed packets or tries to do anything particularly fancy. Enabling port mirroring could be a workaround if you're using a switch that supports it.

Let me know how it goes - I only have a single receiving card so haven't been able to test with multiple yet.

**Comment by jannoke** [comment]
To confirm - there is no problem to use USB card on RPi 3 Model A+. There is also no problem running VLANS  to control multiple panels by specifying vlan interface as outgoing device. Just need management switch and all good. Running 3 VLANS to control 4 panels.

edit:
Running:
2 * 32x16 panels (one channel, same content)
2 * 32x16x8 (effective 64x64 panel) (2 channels,m different content)
